### ISSUE TITLE
No Speakable Text Present Error

### ISSUE THREAD

**Issue by mehall123** [mehall123/Continuing-Professional-Development-App#1]
Added a floating action button and got this error messsage activity_home.xml

**Comment by CorkyDork** [comment]
Will look into this

**Comment by CorkyDork** [comment]
After cloning the current code of the project I was not able to find this issue in the file activity_home.xml

I assume the code where this issue resides is not yet pushed to GitHub.

I did some digging online and found some similar problems and a fix to this problem. Please check this page: https://stackoverflow.com/questions/69142705/no-speakable-text-present-at-android-studio

**Comment by mehall123** [comment]
Oh I see putting in android:hint="eg 01/01/2001" in editTextDate fixes the issue
